name: widgetbook_workspace
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  convex_bottom_bar: ^3.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  rhythm_wave_app:
    path: ../
  widgetbook: ^3.10.1
  widgetbook_annotation: ^3.2.0
  syncfusion_flutter_datepicker: ^27.2.5
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  widgetbook_generator: ^3.9.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/videos/

  fonts:
    - family: ibmPlexSansThai
      fonts:
        - asset: assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Thin.ttf
          weight: 100
        - asset: assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Light.ttf
          weight: 300
        - asset: assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Regular.ttf
          weight: 400
        - asset: assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Medium.ttf
          weight: 500
        - asset: assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Bold.ttf
          weight: 700

    - family: acmeGothic
      fonts:
        - asset: assets/fonts/acme_gothic/AcmeGothic-Light.otf
          weight: 300
        - asset: assets/fonts/acme_gothic/AcmeGothic-Regular.otf
          weight: 400
        - asset: assets/fonts/acme_gothic/AcmeGothic-SemiBold.otf
          weight: 600

    - family: acmeGothicWide
      fonts:
        - asset: assets/fonts/acme_gothic/AcmeGothicWide-Light.otf
          weight: 300
        - asset: assets/fonts/acme_gothic/AcmeGothicWide-Regular.otf
          weight: 400
        - asset: assets/fonts/acme_gothic/AcmeGothicWide-SemiBold.otf
          weight: 600
        - asset: assets/fonts/acme_gothic/AcmeGothicWide-Bold.otf
          weight: 700
        - asset: assets/fonts/acme_gothic/AcmeGothicWide-Black.otf
          weight: 900

    - family: acmeGothicExtraWide
      fonts:
        - asset: assets/fonts/acme_gothic/AcmeGothicExtraWide-Light.otf
          weight: 300
        - asset: assets/fonts/acme_gothic/AcmeGothicExtraWide-Regular.otf
          weight: 400
        - asset: assets/fonts/acme_gothic/AcmeGothicExtraWide-SemiBold.otf
          weight: 600
        - asset: assets/fonts/acme_gothic/AcmeGothicExtraWide-Bold.otf
          weight: 700
        - asset: assets/fonts/acme_gothic/AcmeGothicExtraWide-Black.otf
          weight: 900
